services:
  app:
    build: .
    container_name: api
    ports:
      - "8000:8000" # Maps port 8000 on the host to port 8000 in the container
    # command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app # Mounts the current directory to /app in the container for live code reloading
